services:
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: pytest tests
    volumes:
      - ${PWD}:/home/python
  docs:
    build:
      context: .
      dockerfile: ops/docs.Dockerfile
    command: ops/generate_docs.sh
    volumes:
      - ${PWD}:/home/python

